# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Reachability'
  pod 'SwiftMessages'
  pod 'Alamofire'
  pod 'TWMessageBarManager'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'ProgressHUD'
  pod 'IQKeyboardManagerSwift'


end
